const Base=[
    {   categorie:'Société',
        title:'Escroquerie: Un agent du Port gruge 3 millions à son collègue',
        image_url:'https://www.leral.net/photo/art/default/67970777-47937308.jpg?v=1665593277',
        content:'Électromécanicien de son état, Mohamed Cissé a roulé dans la farine son collègue Seydou Diagne. Il a simulé un prêt de 3 millions FCfa pour l’achat d’un camion. En réalité, l’agent du Port autonome de Dakar (PAD) a remis l’argent à un charlatan qui lui avait promis de le rendre riche. C’est plus tard que la partie civile a découvert le mensonge. Ainsi, Seydou Diagne a décidé de traduire son collègue en justice pour escroquerie.Mohamed Bachir Cissé, âgé de 43 ans, a comparu hier au tribunal de Grande Instance de Dakar pour escroquerie portant sur un montant de 3 millions de francs Cfa. Mais, cet habitant de Guédiawaye nie les faits qui lui sont reprochés. D’après lui, il est question de prêt avec un intérêt de 2 millions de francs. Pourtant, à l’enquête préliminaire, il avait fait des aveux circonstanciés à savoir que l’histoire de l’acquisition du camion pour recevoir les 3 millions est une fiction.Ainsi, il dit être victime d’un marabout qui devait lui fournir de faux billets de banque. Il a d’ailleurs, déposé une plainte à la brigade spéciale du Port et l’affaire sera plaidée le 18 octobre 2022.Des allégations balayées d’un revers de main par le plaignant qui détient toutes les discussions dans son Whatsapp. Seydou Diagne réclame 5 millions en guise de réparation.Finalement, le prévenu a été condamné à 2 mois de prison ferme. En plus de la peine, il devra payer 4 millions FCfa pour la réparation du préjudice.',
        author:'Youssou Wade', 
        id:1   
    },
    {    categorie:'Société',
        title:'Diamaguène Sicap Mbao: Un boucher tranche la gorge de son ami pour 10 000 FCfa',
        image_url:'https://www.leral.net/photo/art/default/67962809-47932302.jpg?v=1665573711',
        content:'Drame à Diamaguène Sicap Mbao où M. Diamanka a tranché la gorge de A. Mbengue âgé de 23 ans avec un tesson de bouteille. Quid du mobile du crime ?Libération’’ parle d’un retard de livraison de chanvre indien. A en croire le journal, ce boucher de 27 ans avait remis à Mbengue 10 000 F Cfa pour son approvisionnement en drogue, mais la victime aurait utilisé l’argent à d’autres fins.Diamanka est en garde à vue au poste de police de Diamaguène Sicap Mbao depuis dimanche dernier.',
        author:'Pape SARR',
        id:2    
    },
    {    categorie:'Société',
        title:'Escroquerie: 4 agents de la Senelec escroqués à plus de 9 millions francs',
        image_url:'https://www.leral.net/photo/art/default/67962609-47932237.jpg?v=1665573088',
       content:"L’arnaque sur l’acquisition de terrains est devenue monnaie courante. Ingénieur demeurant à Pikine, AMS a cédé des terrains du Domaine national à PK et ses trois collègues. C’est pourquoi ceux-ci n’ont pu disposer des documents administratifs afférents aux parcelles depuis 2018. Toutes leurs tentatives sont restées vaines.Sans argent, sans terrain, les quatre agents de la Senelec ont porté l’affaire devant Dame justice. Appréhendé, AMS a comparu hier, devant le tribunal de Dakar pour abus de confiance, escroquerie, faux et usage de faux. Prenant la parole en premier, PK a informé avoir versé 3.775.000 francs au prévenu. Elle a ajouté avoir mis en relation ce dernier et les autres parties civiles.« Depuis 2018, nous ne parvenons pas à entrer en possession de nos terrains. Au niveau des impôts et domaines, on nous a dit que les terrains ne sont pas valables. Ils nous ont recommandé d’aller à la mairie de Sangalkam. On a tout fait pour avoir les contacts du maire. Finalement, on a été mis en rapport avec son adjoint. Malheureusement, on n’a pas pu le rencontrer.Entre-temps, mes collègues ont dit qu’ils souhaitent recouvrer leur argent », a relaté Mme Kane qui a reçu une avance de 2 millions de francs. MS, AD et FBH ont été grugés respectivement de 3 millions, 1 million et 2 millions francs. D’après la dernière nommée, les terrains se situent à Niakhirat. Le comparant leur avait promis les titres de propriété, après versement du montant de 2 millions de francs.D'après Rewmi, , AMS a de son côté, dégagé en touche le faux. Il a reconnu toutefois avoir demandé à PK de le mettre en rapport avec des clients. « Le site est constitué de 20 parcelles de 150m2. Quand on a vu le receveur, il nous a dit que les terrains sont du Domaine national et qu’on doit se rapprocher de la mairie de Sangalkam », a déclaré le père de deux enfants.Selon le représentant du Ministère public, le faux est établi. Car le prévenu a délivré des attestations signées par un receveur. « C’est le receveur du service des domaines de Rufisque qui leur a dit que le document n’est pas valable », a relevé le parquet. Pour la répression du prévenu, il s’est rapporté à la sagesse du tribunal. Le conseil de la défense a écarté le faux, avant de solliciter une application bienveillante de la loi. Relaxé du délit de faux, le prévenu a été condamné à six mois de prison avec sursis et à rembourser les parties civiles",
       author:'Djiby POUYE',
       id:3
    
    },
    {   categorie:'Sport',
    title:'Tournoi UFOA/A U17 : Les Lionceaux perdent la finale aux tirs au but face au Mali',
    date_pub:'15/10/2022',
    image_url:'https://senegal7.com/wp-content/uploads/2022/10/Capture-4.gif.webp',
    contenu:'En finale du tournoi UFOA/A U17 ce dimanche, l’Equipe Nationale U17 du Sénégal s’est inclinée aux tirs au but face au Mali (2-4), après un score de parité à l’issue du temps réglementaire (1-1). Les Lionceaux sont tout de même qualifiés pour la prochaine CAN de la catégorie.L’Équipe Nationale U17 du Sénégal n’imitera pas les U20 il y a quelques semaines dans le même stade. En Mauritanie ce dimanche 9 octobre, les Lionceaux entraînés par Serigne Saliou Dia ont une nouvelle fois mordu la poussière face au Mali qui, bourreau du Sénégal en phase de groupes dans cette même compétition, remporte la finale du Tournoi UFOA/A. Après un 1-1 au bout des 90 minutes, le Sénégal est tombé aux tirs au but.Dès les premières minutes, les Maliens font preuve d’une énorme agressivité et exercent un pressing haut pour empêcher au Sénégal de développer son jeu et de bien huiler sa première relance. Sans surprise donc, le ballon est malien, comme durant une bonne partie dans la rencontre. De plus, mis à part une belle opportunité sénégalaise en tout début de première période, les meilleures situations sont en faveur des Maliens.',
    auteur:'Wiwsport avec Senegal7',
    id:1
},
{   categorie:'Sport',
    title:'Coupe du monde : Diattara et coach Cissé à la conquête du sacre mondial',
    date_pub:'14/10/2022',
    image_url:'https://senegal7.com/wp-content/uploads/2022/10/DohJJDX-750x430.png.webp',
    contenu:'Le ministre des Sports, Yankhoba Diattara et le sélectionneur de l’équipe nationale A du Sénégal, Aliou Cissé étaient en audience, ce vendredi 7 octobre. Une rencontre au cours de laquelle les deux hommes se sont fixés des objectifs en direction de la prochaine coupe du monde Qatar 2022. « Nous avons eu des échanges très cordiaux et riches sur la gestion de l’équipe et surtout de la préparation de la Coupe du monde Qatar2022 avec comme objectif de ramener la Coupe« , a notamment posté le tout nouveau ministre des Sports.PolémiqueLa nomination de Yankhoba Diattara comme nouveau ministre des Sports, lors du dernier remaniement du gouvernement, en remplacement à Matar Ba a suscité une vive polémique notamment chez les acteurs du Sport. Au-delà du record de longévité au ministère, ce dernier était beaucoup plébiscité dans le domaine du Sport. D’aucuns n’ont surtout pas compris le choix du président de la République à seulement deux mois de la compétition mondiale.',
    auteur:'Ousmane Ndiaye – Senegal7',
    id:2
},
{   categorie:'Sport',
    title:'Ligue des champions : Sadio Mané dans le onze type de la semaine',
    date_pub:'15/10/2022',
    image_url:'https://senegal7.com/wp-content/uploads/2022/10/Mane-1.gif.webp',
    contenu:'troisième journée des phases de poules de la ligue des champions, l’UEFA a dévoilé son onze type de la semaine dont   figure Sadio Mané. L’international Sénégalais ,Sadio Mané , auteur de son premier  but en Ligue des champions pour la saison 2022-2023 face à Victoria Plzen de Modou Ndiaye . Il a aussi délivré une passe décisive à Leroy Sané . L’ancien grenats est entré dans le cercle fermé des joueurs Africains  ayant atteint la barre des  25 buts en C1.',
    auteur:'Pape Ibrahima Ndiaye-Senegal7',
    id:3
},
{   categorie:'Sport',
    title:'Serie A : Boulaye Dia délivre la Salernitana contre Hellas Vérone avec son 4e but',
    date_pub:'14/10/2022',
    image_url:'https://senegal7.com/wp-content/uploads/2022/10/Boulaye.gif.webp',
    contenu:'La Salernitana a arraché la victoire sur sa pelouse, ce dimanche après-midi, face à l’Hellas Vérone (2-1). Boulaye Dia a inscrit le but victorieux en toute fin de match.Sans victoire depuis cinq matchs, dont deux défaites de rang, la Salernitana s’est relancée ce dimanche. A l’occasion de la 9e journée de Serie A, les Grenats ont arraché les trois points au Stade Arigis devant l’Hellas Vérone. Et il a fallu l’entrée en jeu de Boulaye Dia pour que les hommes de Davide Nicola décrochent leur second succès cette saison.Préféré sur le banc des remplaçants pour débuter la rencontre, l’ancien joueur de Villarreal a effectué une entrée en jeu fracassante. Idéalement servi par Erik Botheim, Boulaye Dia a en effet fait exploser les supporters de son équipe en marquant un boulet de canon dans les arrêts. Son 4e but en Serie A est donc synonyme de victoire et d’une 11e place pour la Salernitana.',
    auteur:'Senegal7',
    id:4
},
{   categorie:'Sport',
    title:'Chelsea : Edouard Mendy, héros déchu des Blues',
    date_pub:'18/10/2022',
    image_url:'https://senegal7.com/wp-content/uploads/2022/10/edu.gif.webp',
    contenu:'Acteur majeur du sacre surprise de Chelsea en Ligue des champions en 2021, le gardien Edouard Mendy semble avoir perdu son poste de titulaire avant le déplacement à l’AC Milan mercredi (21h00), alors que le Mondial 2022 se profile avec le Sénégal.Arrivé à l’été 2020 de Rennes pour une trentaine de millions d’euros, au milieu de grands noms comme Timo Werner, Kai Havertz, Hakim Ziyech ou Thiago Silva, Mendy semblait presque un intrus. Âgé de 28 ans, il était considéré comme une doublure chargée de mettre la pression sur l’Espagnol Kepa Arrizabalaga, acheté 80 millions d’euros deux ans plus tôt, mais qui semblait n’avoir jamais digéré son image de gardien le plus cher du monde. Arrivé sur le tard au plus haut niveau, le conte de fée de Mendy s’est alors écrit à Londres, où sa sûreté de main et ses réflexes sur sa ligne ont rapidement fait merveille. Frank Lampard en a fait son titulaire dès la 4e journée de championnat puis son successeur Thomas Tuchel, à son arrivée en janvier 2021, l’a confirmé dans son rôle avec à la clé des prestations de très haut niveau.',
    auteur:'DakarActu',
    id:5
},
{   categorie:'Economique',
      id:1,
title:'Attractivité pour le commerce : Le Sénégal classé 18è en Afrique (Bloom Consulting)',
image_url:'https://senegal7.com/wp-content/uploads/2022/10/R-1-750x430.jpg.webp',
content:'Le Sénégal est classé 18eme en Afrique dans le cadre des pays africains les plus attractifs pour le commerce, selon le cabinet de conseil espagnol Bloom Consulting, spécialisé en Nation Branding.En Afrique, les pays les plus attractifs pour les touristes ne sont pas forcément les plus attractifs pour le commerce. Le Sénégal qui occupe la 18e place en Afrique est classé 110e mondial.Le Nigéria en tête du classement Selon Bloom Consulting, le Nigeria est le pays africain le plus attractif pour le commerce. C’est ce que conclut l’entreprise dans son rapport Country Brand Ranking Trade Edition 2022-2023.EtudeL’étude, comme dans sa version dédiée au tourisme, combine les performances économiques, la stratégie de Nation Branding et la présence en ligne des pays sur les sujets liés au commerce pour évaluer leur attractivité dans le domaine.'
},
{   categorie:'Economique',
      id:2,
title:'Rapport final sur les concertations sur la cherté de la vie: La commission propose des mesures pour la baisse du prix du sucre et la stabilisation de l’offre intérieure',
image_url:'https://www.leral.net/photo/art/default/67937934-47917990.jpg?v=1665493032',
content:'Le ministère du Commerce, de la Consommation, et des PME a publié hier, un rapport final sur les concertations sur la cherté de la vie au Sénégal. Ainsi, la commission a fait des propositions de mesures pour la baisse du prix du sucre et la stabilisation de l’offre intérieure. Elle propose de maintenir le principe de la réfaction de base en faisant passer le taux effectif de la TVA de 4,71% à 1%, d "explorer l " option de la suspension de la TVA, de réduire le montant des frais de transit de 12 000 à 3000 FCfa (Niche), de réduire les frais bancaires de 11 000 a 4 000 FCfa (1.5% la Tonne), de formuler et adresser une demande écrite à la collectivité concernée, de sensibiliser les autorités communales de Mbane, Richard-Toll et Rosso sur la question, de construire des magasins de stockage à l’aune de la production, de finaliser l’entrepôt en cours de construction de 14.000 T, de faciliter la mise à disposition d’espaces de stockage pour la construction des magasins recommandés, d"augmenter le nombre de tapis pour enrayer la congestion.'
},
{   categorie:'Economique',
      id:3,
title:'Pétrole: La secrétaire américaine au Trésor fustige la baisse de production de l"Opep+',
image_url:'https://www.leral.net/photo/art/default/67919117-47909308.jpg?v=1665420569',
content:" La secrétaire américaine au Trésor estime que la décision de l'Opep+ de réduire sa production de pétrole est « inutile et imprudente » pour l'économie mondiale, et « inappropriée », étant donné le contexte inflationniste et de crise énergétique actuel.Janet Yellen s'inquiète aussi pour les pays en développement, qui font déjà face à de nombreuses difficultés. La secrétaire au Trésor s'exprimait en amont des rencontres annuelles du Fonds monétaire international et de la Banque mondiale la semaine prochaine. Des rencontres centrées sur l'inflation galopante, les politiques des Banques centrales et l'impact économique de la guerre en Ukraine, entre autres.« Je pense que nous allons échanger nos points de vue sur la gestion de ces problèmes et essayer de déterminer si notre action collective est sensée. C'est le mieux qu'on puisse faire dans ce contexte difficile », a dit aussi Janet Yellen.L'ancienne dirigeante de la FED reproche aussi à ses alliés européens d'être « trop lents » à envoyer l'aide financière promise à l'Ukraine pour lui permettre de contrer l'offensive russe. Elle rappelle que les États-Unis ont déjà versé 8,5 milliards de dollars à l'Ukraine et qu'une nouvelle aide de 4,5 milliards vient d'être votée par le Congrès américain. La Commission européenne s'est engagée la semaine dernière à débloquer, le plus rapidement possible, 3 milliards d'euros, dernier versement de l'enveloppe de 9 milliards d'euros d'aide promise à l'Ukraine."

},
{   categorie:'Economique',
      id:4,
title:'Sénégal: Le FMI table sur une croissance de 10% en 2023',
content:'Le Fonds monétaire international (Fmi) indique que la croissance économique devrait rebondir à environ 10% sur la période 2023 et 2024, stimulée par la production de pétrole et de gaz.Le Fmi rejoint la Banque mondiale par rapport aux prévisions, mais il les a légèrement revu à la baisse, nous dit lesoleil.sn. Il indique un taux de 4,7% contre 4,8%, comme le soulignait la Bm.L’inflation a atteint un niveau record sur plusieurs décennies de 11,2 % en août, sous l’effet de la hausse des prix des denrées alimentaires, souligne le communiqué.',
image_url:'https://www.leral.net/photo/art/default/67865487-47887135.jpg?v=1665178745'
},
{   categorie:'Politique',
    id:1,

        title:'Assemblée nationale : La députée, Aminata Touré propose une loi',
        date_pub:'21/10/2022',
        image_url:'https://senegal7.com/wp-content/uploads/2022/10/Aminata-Toure.gif.webp',
        contenu:'Comme elle l’avait promis, la députée non-inscrite Aminata Touré a saisi le Président de l’Assemblée nationale d’une proposition de loi limitant l’exercice de fonctions et responsabilités dans les Institutions de la République en rapport avec l’existence de liens familiaux avec le Président de la République.Une telle loi constituerait une avancée significative de l’amélioration de notre système de gouvernance », assure Aminata Touré.Pour rappel, l’ex premier ministre, Aminata Touré qui était tête de liste de la majorité Benno Bokk Yaakaar aux législatives de juillet dernier et désormais députée non inscrite, est en rupture de ban avec la majorité présidentielle.',
        auteur:'Diaraf DIOUF'
    },
    {   categorie:'Politique',
        id:2,
        title:'Karim Wade est contraint d’accepter l’amnistie',
        date_pub:'14/10/2022',
        image_url:'https://senegal7.com/wp-content/uploads/2021/07/Karim-Wade-2.png.webp',
        contenu:'Il ne sert plus à rien de refaire le procès de Karim Wade. Tout le monde sait qu’il a été accusé, jugé et condamné sans qu’aucune preuve ne soit mise sur la table. Les faits, pour lesquels il était poursuivi, relevaient de l’imaginaire et personne n’en disconvient. Il ne fait pas l’ombre d’aucun doute que sa condamnation, qui avait un soubassement politique, avait pour objectif de le neutraliser pour l’empêcher de se présenter en 2019 vu qu’il était le principal challenger du Président Macky Sall lors de la précédente présidentielle.Donc, si ce dernier revient aujourd’hui pour corriger sa faute, on ne peut que s’en réjouir. On n’amnistie pas une personne mais des faits et tous les Sénégalais savent que Karim n’a rien fait des faits qu’on lui reproche car accusé sans preuve donc where is the problem?Exiger la révision de son procès à l’heure actuelle relève de l’utopie ou de la prétention démesurée pour plusieurs raisons.Premièrement, la politique c’est avant tout une question de rapport de force. Et de ce point de vue, le Pds n’a pas les moyens de contraindre Macky Sall à réviser son procès.',
        auteur:'Aminata BA'
    },
    {   categorie:'Politique',
        id:3,
        title:'Transport aérien : Air Sénégal suspend ses vols à destination de l’Afrique Centrale, à compter du 30 octobre',
        date_pub:'15/10/2022',
        image_url:'https://www.leral.net/photo/art/grande/67916216-47908244.jpg?v=1665415187',
        contenu:'La compagnie Air Sénégal a annoncé, lundi, la suspension de ses vols entre Dakar et Cotonou-Douala-Libreville, à compter du 30 octobre 2022. "APS"Dans un communiqué, la compagnie indique que "cette décision est justifiée par les faibles performances financières de cette ligne en triangulaire, depuis le lancement en mars 2021". Air Sénégal qui présente "ses excuses aux passagers pour la perturbation occasionnée par cette décision", dit prévoir offrir une alternative aux voyageurs ayant déjà acheté leurs billets.',
        auteur:'Leral'
    },
    {   categorie:'Politique',
        id:4,
        title:'Présidentielle 2024 : Mimi Touré menace de poursuivre Macky Sall et Ismaïla Madior Fall à la CPI si...',
        date_pub:'15/10/2022',
        image_url:'https://www.leral.net/photo/art/default/67906012-47901242.jpg?v=1665376739',
        contenu:'S’il y a perte en vies humaines lors de la tentative d’un 3e mandat de Macky Sall, Ismaïla Madior Fall sera poursuivi devant la Cour Pénale Internationale pour instigation et complicité de crime contre l’Humanité, rapporte un communiqué de sa cellule de communication parvenu à Leral.Selon le document, "Lui qu’elle a recruté en 2012 comme consultant lorsqu’elle était Garde des Sceaux et l a présenté au Président Macky Sall qui ne le connaissait ni d’Adam ni d’Eve. Que Ismaïla Madior Fall qui ne connaît visiblement pas la reconnaissance du ventre, se le tienne pour dit : non seulement ses menaces n’ont aucun effet sur la détermination de Mme Aminata Touré à poursuivre ses activités de député au service exclusif du Peuple sénégalais, mais surtout, qu’il sache que lui Ismaïla Madior Fall qui se vante d’être un tailleur de Constitution de luxe, sera poursuivi devant la Cour Pénale Internationale comme instigateur et complice de crimes contre l’humanité, si des pertes en vies humaines intervenaient à l’occasion d’un troisième mandat juridiquement et moralement inacceptable du Président Macky Sall. A titre de prévention, ladite Cour sera saisie ainsi que le Conseil des Droits de l’Homme afin que notre pays ne revive pas la situation de 2012, où onze de nos compatriotes ont perdu la vie lors des manifestations contre le troisième mandat du Président Abdoulaye Wade".',
        auteur:'Leral'
    },
    {   categorie:'Politique',
        id:5,
        title:'Serigne Moustapha Sy défie Macky Sall',
        date_pub:'15/10/2022',
        image_url:'https://www.leral.net/photo/art/default/67890457-47895933.jpg?v=1665306461',
        contenu:'Le guide spirituel des Moustarchidine, à l’occasion de la célébration du Mawlid aux champs de courses ce samedi, n a pas hésité à se frayer une brèche pour lancer des piques à ses détracteurs. Pour Serigne Moustapha Sy, Macky Sall, son seul adversaire, ne l’empêchera pas de se hisser plus haut et d’atteindre enfin ses objectifs. « Je ne sais pas qui va nous jouer un sale tour, mais je suis sûre que ça ne sera pas Macky Sall. D’ailleurs, avant-hier, quand il est venu rendre visite au Khalife, il n’a pas osé passer devant chez moi pendant que les gens ici vont le huer. Je ne suis pas indiscipliné » a avancé Serigne Moustapha Sy devant les fidèles et devant la coalition Yewwi Askan Wi à qui il conseille de resserrer la ceinture car, l’assemblée nationale doit être le cadet de leurs soucis.L année 2024, tout proche, le guide spirituel des Moustarchidines est convaincu de son engagement et celui de ses alliés de la coalition Yewwi Askan Wi. Il appelle à faire face aux obstacles car, dira-t-il, « ils seront nombreux, mais les capacités de les esquiver sont réelles ».',
        auteur:'DakarActu'
    }
]
export default Base;