const Data_eco=[
    {   categorie:'Economiaue',
        title:'Attractivité pour le commerce : Le Sénégal classé 18è en Afrique (Bloom Consulting)',
        image_url:'https://senegal7.com/wp-content/uploads/2022/10/R-1-750x430.jpg.webp',
        content:'Le Sénégal est classé 18eme en Afrique dans le cadre des pays africains les plus attractifs pour le commerce, selon le cabinet de conseil espagnol Bloom Consulting, spécialisé en Nation Branding.En Afrique, les pays les plus attractifs pour les touristes ne sont pas forcément les plus attractifs pour le commerce. Le Sénégal qui occupe la 18e place en Afrique est classé 110e mondial.Le Nigéria en tête du classement Selon Bloom Consulting, le Nigeria est le pays africain le plus attractif pour le commerce. C’est ce que conclut l’entreprise dans son rapport Country Brand Ranking Trade Edition 2022-2023.EtudeL’étude, comme dans sa version dédiée au tourisme, combine les performances économiques, la stratégie de Nation Branding et la présence en ligne des pays sur les sujets liés au commerce pour évaluer leur attractivité dans le domaine.'
    },
    {   categorie:'Economiaue',
        title:'Rapport final sur les concertations sur la cherté de la vie: La commission propose des mesures pour la baisse du prix du sucre et la stabilisation de l’offre intérieure',
        image_url:'https://www.leral.net/photo/art/default/67937934-47917990.jpg?v=1665493032',
        content:'Le ministère du Commerce, de la Consommation, et des PME a publié hier, un rapport final sur les concertations sur la cherté de la vie au Sénégal. Ainsi, la commission a fait des propositions de mesures pour la baisse du prix du sucre et la stabilisation de l’offre intérieure. Elle propose de maintenir le principe de la réfaction de base en faisant passer le taux effectif de la TVA de 4,71% à 1%, d "explorer l " option de la suspension de la TVA, de réduire le montant des frais de transit de 12 000 à 3000 FCfa (Niche), de réduire les frais bancaires de 11 000 a 4 000 FCfa (1.5% la Tonne), de formuler et adresser une demande écrite à la collectivité concernée, de sensibiliser les autorités communales de Mbane, Richard-Toll et Rosso sur la question, de construire des magasins de stockage à l’aune de la production, de finaliser l’entrepôt en cours de construction de 14.000 T, de faciliter la mise à disposition d’espaces de stockage pour la construction des magasins recommandés, d"augmenter le nombre de tapis pour enrayer la congestion.'
    },
    {   categorie:'Economiaue',
        title:'Pétrole: La secrétaire américaine au Trésor fustige la baisse de production de l"Opep+',
        image_url:'https://www.leral.net/photo/art/default/67919117-47909308.jpg?v=1665420569',
        content:" La secrétaire américaine au Trésor estime que la décision de l'Opep+ de réduire sa production de pétrole est « inutile et imprudente » pour l'économie mondiale, et « inappropriée », étant donné le contexte inflationniste et de crise énergétique actuel.Janet Yellen s'inquiète aussi pour les pays en développement, qui font déjà face à de nombreuses difficultés. La secrétaire au Trésor s'exprimait en amont des rencontres annuelles du Fonds monétaire international et de la Banque mondiale la semaine prochaine. Des rencontres centrées sur l'inflation galopante, les politiques des Banques centrales et l'impact économique de la guerre en Ukraine, entre autres.« Je pense que nous allons échanger nos points de vue sur la gestion de ces problèmes et essayer de déterminer si notre action collective est sensée. C'est le mieux qu'on puisse faire dans ce contexte difficile », a dit aussi Janet Yellen.L'ancienne dirigeante de la FED reproche aussi à ses alliés européens d'être « trop lents » à envoyer l'aide financière promise à l'Ukraine pour lui permettre de contrer l'offensive russe. Elle rappelle que les États-Unis ont déjà versé 8,5 milliards de dollars à l'Ukraine et qu'une nouvelle aide de 4,5 milliards vient d'être votée par le Congrès américain. La Commission européenne s'est engagée la semaine dernière à débloquer, le plus rapidement possible, 3 milliards d'euros, dernier versement de l'enveloppe de 9 milliards d'euros d'aide promise à l'Ukraine."

    },
    {   categorie:'Economiaue',
        title:'Sénégal: Le FMI table sur une croissance de 10% en 2023',
        content:'Le Fonds monétaire international (Fmi) indique que la croissance économique devrait rebondir à environ 10% sur la période 2023 et 2024, stimulée par la production de pétrole et de gaz.Le Fmi rejoint la Banque mondiale par rapport aux prévisions, mais il les a légèrement revu à la baisse, nous dit lesoleil.sn. Il indique un taux de 4,7% contre 4,8%, comme le soulignait la Bm.L’inflation a atteint un niveau record sur plusieurs décennies de 11,2 % en août, sous l’effet de la hausse des prix des denrées alimentaires, souligne le communiqué.',
        image_url:'https://www.leral.net/photo/art/default/67865487-47887135.jpg?v=1665178745'
    }
]
export default Data_eco;