const Data_soc=[
    {   categorie:'Société',
        title:'Escroquerie: Un agent du Port gruge 3 millions à son collègue',
        image_url:'https://www.leral.net/photo/art/default/67970777-47937308.jpg?v=1665593277',
        content:'Électromécanicien de son état, Mohamed Cissé a roulé dans la farine son collègue Seydou Diagne. Il a simulé un prêt de 3 millions FCfa pour l’achat d’un camion. En réalité, l’agent du Port autonome de Dakar (PAD) a remis l’argent à un charlatan qui lui avait promis de le rendre riche. C’est plus tard que la partie civile a découvert le mensonge. Ainsi, Seydou Diagne a décidé de traduire son collègue en justice pour escroquerie.Mohamed Bachir Cissé, âgé de 43 ans, a comparu hier au tribunal de Grande Instance de Dakar pour escroquerie portant sur un montant de 3 millions de francs Cfa. Mais, cet habitant de Guédiawaye nie les faits qui lui sont reprochés. D’après lui, il est question de prêt avec un intérêt de 2 millions de francs. Pourtant, à l’enquête préliminaire, il avait fait des aveux circonstanciés à savoir que l’histoire de l’acquisition du camion pour recevoir les 3 millions est une fiction.Ainsi, il dit être victime d’un marabout qui devait lui fournir de faux billets de banque. Il a d’ailleurs, déposé une plainte à la brigade spéciale du Port et l’affaire sera plaidée le 18 octobre 2022.Des allégations balayées d’un revers de main par le plaignant qui détient toutes les discussions dans son Whatsapp. Seydou Diagne réclame 5 millions en guise de réparation.Finalement, le prévenu a été condamné à 2 mois de prison ferme. En plus de la peine, il devra payer 4 millions FCfa pour la réparation du préjudice.',
        author:'Youssou Wade'    
    },
    {    categorie:'Société',
        title:'Diamaguène Sicap Mbao: Un boucher tranche la gorge de son ami pour 10 000 FCfa',
        image_url:'https://www.leral.net/photo/art/default/67962809-47932302.jpg?v=1665573711',
        content:'Drame à Diamaguène Sicap Mbao où M. Diamanka a tranché la gorge de A. Mbengue âgé de 23 ans avec un tesson de bouteille. Quid du mobile du crime ?Libération’’ parle d’un retard de livraison de chanvre indien. A en croire le journal, ce boucher de 27 ans avait remis à Mbengue 10 000 F Cfa pour son approvisionnement en drogue, mais la victime aurait utilisé l’argent à d’autres fins.Diamanka est en garde à vue au poste de police de Diamaguène Sicap Mbao depuis dimanche dernier.',
        author:'Pape SARR'    
    },
    {    categorie:'Société',
        title:'Escroquerie: 4 agents de la Senelec escroqués à plus de 9 millions francs',
        image_url:'https://www.leral.net/photo/art/default/67962609-47932237.jpg?v=1665573088',
       content:"L’arnaque sur l’acquisition de terrains est devenue monnaie courante. Ingénieur demeurant à Pikine, AMS a cédé des terrains du Domaine national à PK et ses trois collègues. C’est pourquoi ceux-ci n’ont pu disposer des documents administratifs afférents aux parcelles depuis 2018. Toutes leurs tentatives sont restées vaines.Sans argent, sans terrain, les quatre agents de la Senelec ont porté l’affaire devant Dame justice. Appréhendé, AMS a comparu hier, devant le tribunal de Dakar pour abus de confiance, escroquerie, faux et usage de faux. Prenant la parole en premier, PK a informé avoir versé 3.775.000 francs au prévenu. Elle a ajouté avoir mis en relation ce dernier et les autres parties civiles.« Depuis 2018, nous ne parvenons pas à entrer en possession de nos terrains. Au niveau des impôts et domaines, on nous a dit que les terrains ne sont pas valables. Ils nous ont recommandé d’aller à la mairie de Sangalkam. On a tout fait pour avoir les contacts du maire. Finalement, on a été mis en rapport avec son adjoint. Malheureusement, on n’a pas pu le rencontrer.Entre-temps, mes collègues ont dit qu’ils souhaitent recouvrer leur argent », a relaté Mme Kane qui a reçu une avance de 2 millions de francs. MS, AD et FBH ont été grugés respectivement de 3 millions, 1 million et 2 millions francs. D’après la dernière nommée, les terrains se situent à Niakhirat. Le comparant leur avait promis les titres de propriété, après versement du montant de 2 millions de francs.D'après Rewmi, , AMS a de son côté, dégagé en touche le faux. Il a reconnu toutefois avoir demandé à PK de le mettre en rapport avec des clients. « Le site est constitué de 20 parcelles de 150m2. Quand on a vu le receveur, il nous a dit que les terrains sont du Domaine national et qu’on doit se rapprocher de la mairie de Sangalkam », a déclaré le père de deux enfants.Selon le représentant du Ministère public, le faux est établi. Car le prévenu a délivré des attestations signées par un receveur. « C’est le receveur du service des domaines de Rufisque qui leur a dit que le document n’est pas valable », a relevé le parquet. Pour la répression du prévenu, il s’est rapporté à la sagesse du tribunal. Le conseil de la défense a écarté le faux, avant de solliciter une application bienveillante de la loi. Relaxé du délit de faux, le prévenu a été condamné à six mois de prison avec sursis et à rembourser les parties civiles",
       author:'Djiby POUYE'
    
    }
]
export default Data_soc;